### ISSUE TITLE
Unable to build graphql-schema-diff

### ISSUE THREAD

**Issue by shipswake** [fabsrc/graphql-schema-diff#119]
I am trying to use graphql-schema-diff in both e React app and a Docusaurus app.

After adding the NodePolyfillPlugin I can remove the webpack5 errors

I am not able to build and I receive the error:

ModuleNotFoundError: Module not found: Error: Can't resolve 'module' in 'C:\Code\Documentation\ui-test\node_modules\@graphql-tools\load\cjs\load-typedefs'

**Comment by fabsrc** [comment]
This package is not designed for use in a browser, so it likely won't function correctly in a frontend application. However, you might be able to make it work by extracting the necessary code for your use case from the `diff.ts` file and removing the node-specific code.
