### ISSUE TITLE
Syntax highlighting in html view

### ISSUE THREAD

**Issue by mariusc23** [fabsrc/graphql-schema-diff#14]
Hi again! It would be great if syntax highlighting could be added to the html view. Perhaps matching graphiql coloring. Some ideas:
- descriptions could be gray
- properties blue
- values orange

**Comment by fabsrc** [comment]
Just saw that there is a PR which adds GraphQL syntax highlighting to highlight.js (https://github.com/highlightjs/highlight.js/pull/3448).
After that PR is merged and released I can update `graphql-schema-diff` to enable GraphQL syntax highlighting.
