### ISSUE TITLE
Publish the latest code to npm

### ISSUE THREAD

**Issue by maximkoretskiy** [fabsrc/graphql-schema-diff#33]
I see that the last code changes are not available in npm, while they introduce deps security updates. 

I would ignore creating an issue and use npm `override` setting to fix it in my repository, but `npm-shrinkwrap.json` in the repo blocks me from `override` usage. [see](https://github.com/npm/cli/issues/3755)

using [git reference](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#git-urls-as-dependencies) for now .

**Comment by fabsrc** [comment]
I just published version [2.6.1](https://www.npmjs.com/package/graphql-schema-diff/v/2.6.1?activeTab=versions) with the current code from the `master` branch.
