### ISSUE TITLE
Diff misses types that implement interface 

### ISSUE THREAD

**Issue by satshabad-cr** [fabsrc/graphql-schema-diff#7]
If have a schema like so, and a GraphQL implementation to match
```
type Query {
  foo: Bar
}

interface Bar {
  someField: String
}

type Baz implements Bar {
  someField: String
}
```

The differ misses Baz from the implementation completely

**Comment by satshabad-cr** [comment]
and If I reference Baz directly, the differ finds it

**Comment by fabsrc** [comment]
Hi @satshabad-cr 
Could you please post both schemas you're trying to compare?

**Comment by satshabad-cr** [comment]
Sorry, I figured it out. I needed to register the types with the graphene library manually!
